clip_model: "openai/clip-vit-base-patch32"
clip_dim: 512
projection_dim: 256
patch_size: 32
embed_dim: 256

device: 'cuda'
batch_size: 64
lr: 0.0001
epochs: 50
temp: 0.07  # SupCon 温度系数
lambda_supcon: 0.5 # 语义聚类损失权重
save_path: './checkpoints'
