clip_model: "/root/autodl-tmp/detection/models/clip-vit-base-patch32/" # clip-vit-base-patch32
#clip_dim: 512
projection_dim: 256
patch_size: 32
embed_dim: 256

seed: 3407 # 42
device: 'cuda'
batch_size: 256   # 512
lr: 0.0004        # 0.0001
epochs: 100
temp: 0.07  # SupCon 温度系数
lambda_supcon: 0 # 语义聚类损失权重 0.5
save_path: './checkpoints'
logs_path: './logs'
resume_epoch: 3 # 举例：你想从第 {resume_epoch} epoch 继续，{不包括resume_epoch}，{从resume_epoch}+1开始;重新开始为0
#exp_name: exp_20260115_191220_seed3407
use_lora: True    # 是否使用 LoRA 微调，False 则为解冻少部分参数。建议使用 True
# 可选值: 'concat' | 'discrepancy' | 'gating'
fusion_type: 'gating'
# 正交损失权重 (仅在 gating 模式下生效)
lambda_orth: 0.001
lambda_gate: 0.01
lambda_decorr: 0.001
lambda_l1: 0.0001
# 推理：
# 验证集目录，多个用','隔开
VAL_DIRS: "/root/autodl-tmp/data/val,/root/autodl-tmp/adm/val,/root/autodl-tmp/biggan/val,/root/autodl-tmp/glide/val,/root/autodl-tmp/midjourney/val,/root/autodl-tmp/sdv5/val,/root/autodl-tmp/vqdm/val,/root/autodl-tmp/wukong/val"
# 模型权重目录，默认目录下所有权重文件，
CHECKPOINT_DIR: "/root/autodl-tmp/detection/checkpoints/exp_20260121_003138_seed3407"
# 模型权重目录下的epoch权重，只使用这一个，注释掉使用所有
CHECKPOINT_EPOCH: 20
